"""
Step 5: Generate a human-readable placement report in Markdown.
"""

import json
from pathlib import Path
from datetime import datetime


def score_bar(score: float, width: int = 10) -> str:
    filled = round(score * width)
    return "█" * filled + "░" * (width - filled)


def run(placement_file: str = "placement_plan.json", output_file: str = "placement_report.md"):
    with open(placement_file) as f:
        placements = json.load(f)

    lines = [
        "# 🎨 Art Placement Report",
        f"*Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}*",
        "",
        f"**{len(placements)} placement recommendation(s)** based on color harmony, style compatibility, room type, and mood matching.",
        "",
        "---",
        "",
    ]

    for i, p in enumerate(placements):
        score = p.get("score", 0)
        bd = p.get("score_breakdown", {})

        lines += [
            f"## Placement {i+1}: *{p.get('art_title', 'Artwork')}*",
            "",
            f"**Room:** {p.get('room_type', '?').title()}  |  **Wall:** {p.get('wall_id', '?')}  |  **Overall Match:** {score:.0%}",
            "",
            "### Score Breakdown",
            f"| Factor | Score | Bar |",
            f"|--------|-------|-----|",
            f"| Color Harmony       | {bd.get('color_harmony', 0):.0%} | {score_bar(bd.get('color_harmony', 0))} |",
            f"| Style Compatibility | {bd.get('style_compatibility', 0):.0%} | {score_bar(bd.get('style_compatibility', 0))} |",
            f"| Room Type Match     | {bd.get('room_type_match', 0):.0%} | {score_bar(bd.get('room_type_match', 0))} |",
            f"| Mood Match          | {bd.get('mood_match', 0):.0%} | {score_bar(bd.get('mood_match', 0))} |",
            "",
            "### Design Rationale",
            f"- **Art style:** {p.get('art_style', 'N/A')}  |  **Mood:** {p.get('art_mood', 'N/A')}",
            f"- **Recommended framing:** {p.get('matting', 'N/A')}",
            f"- **Art notes:** {p.get('design_notes', 'N/A')}",
            f"- **Room notes:** {p.get('room_notes', 'N/A')}",
            "",
        ]

        if p.get("output_image"):
            lines += [
                "### Preview",
                f"![Composited result]({p['output_image']})",
                "",
            ]

        lines += ["---", ""]

    lines += [
        "## Tips for Final Installation",
        "",
        "- **Eye level rule:** Hang artwork so its center is 57–60 inches from the floor.",
        "- **Sofa rule:** Art above a sofa should be 2/3 the sofa's width.",
        "- **Lighting:** Add a picture light or directional spot for artwork to pop.",
        "- **Gallery walls:** Maintain 2–3 inch spacing between pieces.",
        "",
        "*Report generated by the Art Placement Pipeline.*",
    ]

    report = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(report)

    print(f"\n  Saved placement report → {output_file}")
    return output_file


if __name__ == "__main__":
    run()
